function [] = network_model_ul_demo_f()

Constants_c.print_configurations();
fprintf(Constants_c.fid, 'start ul network model...\n');
M_eMBB = Constants_c.M_eMBB;
M_veh = Constants_c.M_veh; 
M_mMTC = Constants_c.M_mMTC;

sim_nr_drops_per_round = Constants_c.sim_nr_drops_per_round; 
sim_nr_round = Constants_c.sim_nr_round; 

lambda_e_lst = Constants_c.lambda_e_lst;
avg_prb_utilization_v2x = zeros(length(lambda_e_lst), 1);
avg_prb_utilization_eMBB = zeros(length(lambda_e_lst), 1);
avg_prb_utilization_mMTC = zeros(length(lambda_e_lst), 1);
avg_prb_utilization = zeros(length(lambda_e_lst), 1);

outage_rate_v2x = zeros(length(lambda_e_lst), 1);
outage_rate_eMBB = zeros(length(lambda_e_lst), 1);
outage_rate_mMTC = zeros(length(lambda_e_lst), 1);
outage_rate = zeros(length(lambda_e_lst), 1);

for count = 1 : length(lambda_e_lst)
    lambda_e = lambda_e_lst(count);
    % create the network model for simulation
    nw = Network_Model_ul_c(M_eMBB, M_veh, M_mMTC, lambda_e, sim_nr_drops_per_round, sim_nr_round); 
    % start to run the network model
    [avg_prb_utilization_v2x(count), ...
     avg_prb_utilization_eMBB(count), ...
     avg_prb_utilization_mMTC(count), ...
     avg_prb_utilization(count), ...
     outage_rate_v2x(count), ...
     outage_rate_eMBB(count), ...
     outage_rate_mMTC(count), ...
     outage_rate(count)] = nw.start_simulation();
end

for count = 1 : length(lambda_e_lst)
    fprintf(Constants_c.fid, '%f -> %f %f %f %f %f %f %f %f\n', lambda_e_lst(count), ...
        avg_prb_utilization_v2x(count), ...
        avg_prb_utilization_eMBB(count), ...
        avg_prb_utilization_mMTC(count), ...
        avg_prb_utilization(count), ...
        outage_rate_v2x(count), ...
        outage_rate_eMBB(count), ...
        outage_rate_mMTC(count), ...
        outage_rate(count) ...
        );
end

end

